### ISSUE TITLE
ReadMe UPM Links Broken

### ISSUE THREAD

**Issue by MrGadget1024** [James-Frowen/Mirage.Profiler#8]
Neither of these work in Unity 2021 LTS

![image](https://user-images.githubusercontent.com/9826063/205923362-f21d4721-d7f4-4a80-a60a-27d58dcc5e60.png)

**Comment by James-Frowen** [comment]
I've just checked this in `Unity 2021.3.14` and it seems to work
```json
"com.james-frowen.mirage-profiler": "https://github.com/James-Frowen/Mirage.Profiler.git?path=/Assets/Mirage.Profiler#v1.1.0-mirror.10",
```

which part seems to be broken?

**Comment by MrGadget1024** [comment]
Unity 2021.3.15

![image](https://user-images.githubusercontent.com/9826063/208103830-17efd5b9-3c80-458d-95b7-ae1f1fab8174.png)

**Comment by MrGadget1024** [comment]
If I just use this part it does work.
`https://github.com/James-Frowen/Mirage.Profiler.git?path=/Assets/Mirage.Profiler#v1.1.0-mirror.10`

**Comment by James-Frowen** [comment]
> Unity 2021.3.15
> 
> ![image](https://user-images.githubusercontent.com/9826063/208103830-17efd5b9-3c80-458d-95b7-ae1f1fab8174.png)

can you give steps to reproduce this error?

**Comment by MrGadget1024** [comment]
copy the whole thing to clipboard and paste it into Package Manager "Add package from git URL" produces those errors.

**Comment by James-Frowen** [comment]
That seems to work fine for me, I can't reproduce the error.

**Comment by MrGadget1024** [comment]
URL alone works, whole thing as below, throws errors (in case I wasn't clear above)
`"com.james-frowen.mirage-profiler": "https://github.com/James-Frowen/Mirage.Profiler.git?path=/Assets/Mirage.Profiler#v1.1.0-mirror.10",`

**Comment by James-Frowen** [comment]
I dont think this is a problem with the readme, the "Add package from git URL" implies that it should only use url part not the full string

**Comment by MrGadget1024** [comment]
> I don't think this is a problem with the readme, the "Add package from git URL" implies that it should only use URL part not the full string

Except that when the mouse goes over one of those, there's a handy Copy UI button that appears, that invites you to click it to copy the whole string, which you can't actually use.  That whole string would only be for people wanting to manually hack their manifest files, not paste what got copied into Unity's URL field in the editor's UI.
