### ISSUE TITLE
Errors Importing With v1.1.0-mirror.10

### ISSUE THREAD

**Issue by wesleywh** [James-Frowen/Mirage.Profiler#9]
I'm getting a bunch of errors talking about missing namespaces, there are missing files, and missing virtual methods, etc. 

I have done the following when importing:
1. Added `com.unity.profiling.core` and imported v1.0.2 into my project
2. Added the following line to my manifest.json file:
```
"com.james-frowen.mirage-profiler": "https://github.com/James-Frowen/Mirage.Profiler.git?path=/Assets/Mirage.Profiler#v1.1.0-mirror.10",
```

As soon as it imports I get 28 errors and have a ton of missing files. I have tried importing from the releases page using the UnityPackage and cloning the project and copying the Packages directory to my project with the same errors.

Unity Version: 2020.3.42f
Mirror Version: v72.0.16

Here are some of the errors to give you an idea:
```
Library\PackageCache\com.james-frowen.mirage-profiler@793fbce2d8\Editor\Messages\MessageViewController.cs(33,42): error CS0115: 'MessageViewController.CreateView()': no suitable method found to override
Library\PackageCache\com.james-frowen.mirage-profiler@793fbce2d8\Editor\ServerModule.cs(11,33): error CS0246: The type or namespace name 'ProfilerModule' could not be found (are you missing a using directive or an assembly reference?)
Library\PackageCache\com.james-frowen.mirage-profiler@793fbce2d8\Editor\ServerModule.cs(10,6): error CS0246: The type or namespace name 'ProfilerModuleMetadata' could not be found (are you missing a using directive or an assembly reference?)
Library\PackageCache\com.james-frowen.mirage-profiler@793fbce2d8\Editor\ServerModule.cs(22,54): error CS0115: 'ServerModule.CreateDetailsViewController()': no suitable method found to override
Library\PackageCache\com.james-frowen.mirage-profiler@793fbce2d8\Editor\ServerModule.cs(13,33): error CS0246: The type or namespace name 'ProfilerCounterDescriptor' could not be found (are you missing a using directive or an assembly reference?)
```
The list goes on, this is just an extraction of some of the errors.

Am I missing required dependencies you're not talking about in the README?

**Comment by scorpioservo** [comment]
Also having this issue.

![image](https://github.com/James-Frowen/Mirage.Profiler/assets/22650047/1fb29689-9d04-43a0-954f-93eb3118c962)

**Comment by James-Frowen** [comment]
closing this issue as the Unity Profiling Core API package requires unity 2021.3
